tz: "Asia/Riyadh"

schedule:
  start_hour: 6              # بداية اليوم التشغيلي (ساعة محلية)
  hours_per_day: 18          # كم ساعة نولّد (6→24)
  minute_resolution: 1       # دقة الزمن بالدقيقة

seeds:
  stations_file: "./data/stations.json"
  lines_file: "./data/lines.json"
  weather_file: "./data/weather_patterns.json"
  events_file: "./data/calendar_events.csv"
  holidays_file: "./data/holidays.csv"

fields:
  station_code: "code"
  station_name: "name"
  lines_field: "lines"                       # داخلها عناصر فيها { "line_name": "Blue", ... }
  occupancy_cap_field: "station_occupancy_capacity"
  platform_cap_field: "station_platform_capacity"
  peak_cap_field: "station_capacity_peak"

assumptions:
  avg_dwell_min: 12         # متوسط بقاء الراكب داخل المحطة (لتحويل التدفق إلى تواجد لحظي)

output:
  out_dir: "./out"
  format: "parquet"         # parquet أو csv
  firebase_enabled: false   # نخليها false الآن (نفعّلها لاحقًا لو تبين)
  firebase_path: "masar/days"
